version: '3'
services:

  #PHP Service
  yourhealth:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yourhealth
    restart: unless-stopped
    tty: true
    env_file:
      - .env
    working_dir: /var/www
    volumes:
       - ./:/var/www
       - ./php/php.ini:/usr/local/etc/php.ini
    networks:
      - yourhealth-network

  #Nginx Service
  yourhealth_webserver:
    image: nginx:alpine
    container_name: yourhealth_webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - yourhealth
      - yourhealth_redis
    networks:
      - yourhealth-network

  yourhealth_redis:
    image: redis:6.0.9-alpine
    restart: unless-stopped
    expose:
      - "6379"

#Docker Networks
networks:
  yourhealth-network:
    driver: bridge
