version: '3'
services:

  #PHP Service
  yourhealth:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yourhealth
    restart: unless-stopped
    tty: true
    command: "php artisan serve --host=0.0.0.0 --port 8020"
    ports:
      - 8020:8020
    env_file:
      - .env
    working_dir: /var/www
    volumes:
       - ./:/var/www
       - ./php/php.ini:/usr/local/etc/php.ini
    depends_on:
      - yourhealth_db
    networks:
      - yourhealth-network

  #Postgis Service
  yourhealth_db:
    image: kartoza/postgis:12.0
    container_name: yourhealth_db
    restart: unless-stopped
    tty: true
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql
      - /backups:/interface
    networks:
      - yourhealth-network

  yourhealth_redis:
    image: redis:6.0.9-alpine
    restart: unless-stopped
    expose:
      - "6379"

#Docker Networks
networks:
  yourhealth-network:
    driver: bridge

#Volumes
volumes:
  postgres_data:
    driver: local